CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`fullLegalName` varchar(255),
	`dateOfBirth` varchar(20),
	`ssn` varchar(20),
	`occupation` varchar(255),
	`annualIncome` varchar(100),
	`streetAddress` varchar(500),
	`city` varchar(100),
	`state` varchar(50),
	`zipCode` varchar(20),
	`heightFt` int,
	`heightIn` int,
	`weight` int,
	`medicalConditions` text,
	`medications` text,
	`familyHistory` text,
	`hospitalized` varchar(10),
	`dui` varchar(10),
	`primaryBeneficiary` varchar(255),
	`beneficiaryRelationship` varchar(100),
	`contingentBeneficiary` varchar(255),
	`additionalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`age` int,
	`gender` varchar(20),
	`tobacco` varchar(10),
	`policyType` varchar(50),
	`termLength` int,
	`coverageAmount` int,
	`monthlyPremium` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
